// Built-in default checklist items per visit type.
// Shared between ChecklistTemplates (seed/restore) and VisitWizard (fallback when no template record exists).
// CORE FALLBACK SAFETY: the three core package visit types (Home Watch
// Inspection = Quick Check, Property Care Inspection = Property Care,
// Complete Care Property Visit) ALWAYS have a built-in fallback here — if
// their master template is ever missing or archived, a new visit can never
// silently start with an empty checklist. These mirror the approved master
// package checklists (Quick Check / Property Care / Complete Care walk-through
// scopes). The old legacy lists (31-item Basic, archived 35-item Monthly
// Property Watch) are intentionally NOT restored.
export const SEED = {
  "Monthly Property Watch": ["Gates","Fences","Doors","Windows","Shutters","Roof","Balconies","Exterior walls","Drainage","Storm damage","Signs of forced entry","Water leaks","Humidity","Mold","Unusual odors","Electrical supply","Lights","Air conditioning","Heating","Appliances","Internet","Security system","Insects or pests","Cleanliness","General condition","Pool water level","Pool clarity","Pool equipment","Irrigation","Garden condition","Outdoor lighting","Electricity meter","Water meter","Water pressure","Hot water"],
  "Owner Arrival Preparation": ["Open and air out property","Turn on electricity","Turn on water","Turn on hot water","Start air conditioning","Check refrigerator","Check Wi-Fi","Test lights","Inspect bathrooms","Inspect bedrooms","Prepare linens","Confirm cleaning","Check pool","Check garden","Place welcome items","Confirm keys","Final photo"],
  "Guest Arrival Preparation": ["Open and air out property","Turn on electricity","Turn on water","Turn on hot water","Start air conditioning","Check refrigerator","Check Wi-Fi","Test lights","Inspect bathrooms","Inspect bedrooms","Prepare linens","Confirm cleaning","Check pool","Check garden","Place welcome items","Confirm keys","Final photo"],
  "Departure Inspection": ["Check property after departure","Close windows and shutters","Turn off selected utilities","Check air conditioning","Remove rubbish","Check refrigerator","Confirm cleaning","Inspect for damage","Secure doors and gates","Check alarm","Record keys","Take final photos"],
  // Seasonal Opening/Closing: practical visual property-care scope. Simple
  // controls only with clear written owner instructions; stop-and-ask when
  // unclear or a problem is apparent; specialist work (pool, pipes, water
  // heater, electrical/plumbing, alarms) is coordinated, never performed.
  "Seasonal Opening": ["Complete a visual walkthrough of the property (exterior and interior)","Carry out the property-specific opening steps approved by the owner in advance (recorded on this visit's owner approval)","Operate simple controls (opening/shutting windows and shutters, airing) only where the owner's recorded instructions are clear","Stop any unclear or apparently problematic step, document what is seen, and ask the owner how to proceed","Look for obvious visible problems: leaks or water issues, moisture, damage, or anything unusual after the period away","Air the property as appropriate","Check that doors, shutters and gates are as the owner instructed","Utility systems (water, electricity, pool, water heater, alarms): act only on the owner's recorded property-specific instructions — otherwise flag for the owner or an appropriate provider; never start or adjust automatically","Take documentation photos","Return or store keys according to the owner's recorded key instructions for this visit","Complete the visit record with notes and photos for the owner"],
  "Seasonal Closing": ["Complete a visual walkthrough of the property (exterior and interior)","Carry out the property-specific closing steps approved by the owner in advance (recorded on this visit's owner approval)","Operate simple controls (opening/shutting windows and shutters) only where the owner's recorded instructions are clear","Stop any unclear or apparently problematic step, document what is seen, and ask the owner how to proceed","Look for obvious visible problems: damage, leaks or water issues, or anything unusual","Check that doors, windows and shutters are closed and in visible good condition","Secure the property as the owner has instructed","Utility systems (water, electricity, pool, water heater, alarms): act only on the owner's recorded property-specific instructions — otherwise flag for the owner or an appropriate provider; never start or adjust automatically","Take documentation photos","Return or store keys according to the owner's recorded key instructions for this visit","Complete the visit record with notes and photos for the owner"],
  "Owner Representative Construction Visit": ["Record arrival time and site access","Contractors present","Materials delivered","Work expected","Work observed","Workmanship concerns","Incomplete work","Photos of progress","Questions for owner decision","Record departure time"],
  // Quick Check walk-through scope (short visual check — no routine photos/report required)
  "Home Watch Inspection": ["Quick exterior walk-around","Quick interior walk-through","Doors/gates/windows visibly secure","Look for obvious damage or vandalism","Look for obvious visible water/leaks","Look for obvious pest activity","Confirm electricity appears available where reasonably observable","Quick visual check of grounds/balconies","Quick visual check of pool condition where applicable","Observe obvious moisture/water intrusion encountered during walk-through","Notify owner if a concerning problem is discovered","Take photos of a PROBLEM when a problem is discovered","Confirm property is secured before leaving"],
  // Property Care walk-through scope (visual care + documentation + written report)
  "Property Care Inspection": ["More complete exterior visual check","More complete interior visual walk-through","Doors/gates/windows visibly secure","Look for obvious damage/vandalism","Look for visible water/leaks","Look for pest concerns/signs","Confirm electricity appears available where reasonably observable","Grounds/balconies visual condition","Pool visual condition where applicable","Owner-selected monitoring priorities","Visible moisture/mold observations","Visual checks under accessible sinks for obvious leaks","Routine property photos","Written visit report","Documentation of concerns","Problem photographs when applicable","Owner notification when necessary","Confirm property is secured before leaving"],
  // Complete Care walk-through scope (Property Care depth PLUS limited agreed
  // operational checks and ongoing concern tracking)
  "Complete Care Property Visit": ["More detailed exterior visual review","More detailed interior visual review","Doors/gates/windows visibly secure","Damage/vandalism observations","Visible water/leak observations","Pest concerns/signs","Electricity appears available where reasonably observable","Detailed grounds/balcony visual condition","Detailed pool visual condition where applicable","Visible moisture/mold observations","Visual checks under accessible sinks","Expanded owner-selected monitoring priorities","Routine property photos","More detailed photo documentation","Detailed written visit report","Documentation of concerns","Problem photographs when applicable","Owner notification when necessary","Run agreed/selected faucets","Flush agreed/selected toilets","Operate selected lights","Check whether agreed refrigerator/freezer or other agreed appliances appear to operate","Briefly operate agreed AC units","Visually observe pool equipment condition","Recheck previously identified concerns","Track unresolved concerns","Give priority attention/assistance to identified concerns","Confirm property is secured before leaving"],
  "Grocery Stocking": ["Confirm owner shopping list and budget","Purchase requested groceries","Deliver groceries to the property","Put away / stock basics","Record grocery cost and attach receipt photo","Send owner update with photos"],
  // Complete Care follow-up scope: a SHORT companion check (up to 15 minutes)
  // with a dated photo update for the owner — never a second full visit.
  "Complete Care Follow-up Visit": ["Quick exterior walk-around","Quick interior walk-through","Doors/gates/windows visibly secure","Look for obvious visible water/leaks or moisture","Recheck previously identified concerns","Capture the dated photo update for the owner (1–3 photos)","Confirm property is secured before leaving"],
};

export const VISIT_TYPES = [
  "Monthly Property Watch", "Owner Arrival Preparation", "Guest Arrival Preparation",
  "Departure Inspection", "Seasonal Opening", "Seasonal Closing", "Owner Representative Construction Visit",
  "Home Watch Inspection", "Property Care Inspection", "Complete Care Property Visit", "Complete Care Follow-up Visit", "Emergency Visit", "Owner Representative Site Visit",
  "Initial Property Onboarding Inspection", "Grocery Stocking",
];